import{i as u,S as f}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function p(o){return o.map(r=>`
    <li class="gallery-item">
        <a href="${r.urls.largeImageURL}">
            <img src="${r.urls.webformatURL}" 
            alt="${r.tags}"  title=""/>
        </a>
    </li>`).join("")}function d(o){const r="/api",n="https://pixabay.com",s="44004812-c52c8438ab8e6871c63eadf8f",e=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${n}${r}?${e}`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const m="/goit-js-hw-11/assets/error-d5cf2823.svg",h=document.querySelector(".js-form"),a=document.querySelector(".js-gallery"),c=document.querySelector(".js-backdrop");h.addEventListener("submit",g);function g(o){o.preventDefault(),a.innerHTML="",L();const r=o.currentTarget.elements["search-query"].value.trim();d(r).then(n=>{if(n.results.length===0)return u.error({title:"Error",titleColor:"#fff",messageColor:"#fff",iconUrl:m,message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",position:"topLeft"});a.innerHTML=p(n.results),new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),a.refresh()}).catch(console.log).finally(()=>{b(),o.target.reset()})}//!================================================================
const y={position:"absolute",lines:13,length:44,width:19,radius:46,scale:1.25,corners:1,speed:1,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#2bab81",fadeColor:"transparent",top:"50%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner"},l=new Spinner(y);function L(){l.spin(c),c.classList.remove("is-hidden")}function b(){l.stop(),c.classList.add("is-hidden")}//!================================================================
//# sourceMappingURL=commonHelpers.js.map
